### ISSUE TITLE
Crash on pulling some repositories

### ISSUE THREAD

**Issue by Maldron** [luketheobscure/BlargBucket#18]
Nuke the simulator > Build > Login > Choose the Alpaca repo > Crash

I stepped back in time a bit (mostly out of paranoia that I had introduced it), and it looks like it starts in commit ec661ab (Refactor Events). The logs don't seem super useful, but it does look like it's always dies immediately after fetching /events.

**Comment by luketheobscure** [comment]
Oh gross... Sometimes "description" is a number, sometimes it's a dictionary. Thanks BitBucket. :(

**Comment by luketheobscure** [comment]
Crash is fixed. Leaving this open until some tests are written for it.
